language: node_js
node_js:
  - 12
script:
  - npm run build
  - npm test
branches:
  only:
    - beta
env:
  global:
    PRE_RELEASE: "--preRelease=beta"
after_success:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  - npm run release -- $PRE_RELEASE
