language: node_js
node_js:
  - 12
script:
  - npm run build
  - npm test
branches:
  only:
    - beta
env:
  global:
    PRE_RELEASE: "--preRelease=beta"
    BRANCH: master
after_success:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  - git fetch origin ${BRANCH} --tags
  - git checkout ${BRANCH}
  - git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
  - git config --global user.name "Jenkins Pipeline"
  - git config --global user.email "jenkins@ibmcloud.com"
  - git config --local credential.helper "!f() { echo username=\\$GITHUB_USER; echo password=\\$GITHUB_TOKEN; }; f"
  - npm run release -- $PRE_RELEASE
