name: Asset publish

on:
  release:
    types:
      - published

jobs:
  publish-assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build
        run: npm ci && npm run build

      - name: Install pkg
        run: npm install -g pkg

      - name: Build Asset
        run: pkg -o igc --options no-warnings .

      - name: Upload Linux cli
        id: upload-linux-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./igc-linux-x64
          asset_name: igc-linux
          asset_content_type: application/octet-stream

      - name: Upload Linux x64 cli
        id: upload-linux-x64-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./igc-linux-x64
          asset_name: igc-linux-x64
          asset_content_type: application/octet-stream

      - name: Upload Linux arm64 cli
        id: upload-linux-arm64-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./igc-linux-arm64
          asset_name: igc-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload MacOS cli
        id: upload-macos-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./igc-macos-x64
          asset_name: igc-macos
          asset_content_type: application/octet-stream

      - name: Upload MacOS x64 cli
        id: upload-macos-x64-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./igc-macos-x64
          asset_name: igc-macos-x64
          asset_content_type: application/octet-stream

      - name: Upload MacOS arm64 cli
        id: upload-macos-arm64-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./igc-macos-arm64
          asset_name: igc-macos-arm64
          asset_content_type: application/octet-stream

      - name: Upload Alpine cli
        id: upload-alpine-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./igc-alpine-x64
          asset_name: igc-alpine
          asset_content_type: application/octet-stream

      - name: Upload Alpine x64 cli
        id: upload-alpine-x64-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./igc-alpine-x64
          asset_name: igc-alpine-x64
          asset_content_type: application/octet-stream

      - name: Upload Alpine arm64 cli
        id: upload-alpine-arm64-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./igc-alpine-arm64
          asset_name: igc-alpine-arm64
          asset_content_type: application/octet-stream
